<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Review;
use Carbon\Carbon;

class ReviewSeeder extends Seeder
{
    public function run(): void
    {
        $reviews = [
            //Laptop ID 1
            ['laptop_id' => 1, 'responder_name' => 'HardcoreGamer', 'rating' => 5, 'review' => 'Ryzen 7 + RTX 3060 monster! Bisa main Cyberpunk 2077 di ultra 60fps dengan DLSS. Sayang layar agak backlight bleed.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'WarmLaptopUser', 'rating' => 4, 'review' => 'Performanya kencang, tapi suhu CPU bisa sampai 90°C saat gaming berat. Perlu cooling pad ekstra.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'PortHater', 'rating' => 4, 'review' => 'Konektor USB-C cuma 1, kurang untuk peripheral gaming. Tapi build quality solid!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'BatteryDisappointed', 'rating' => 3, 'review' => 'Baterai cuma tahan 2 jam kalau gaming. Tapi ya emang laptop gaming sih...', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'RGBLover', 'rating' => 5, 'review' => 'Keyboard RGB-nya epic! Performa sesuai harga, rekomendasi buat gamer.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'NoisyFanUser', 'rating' => 4, 'review' => 'Fan nya berisik banget pas turbo mode, tapi performa memang worth it.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'UpgradeMaster', 'rating' => 5, 'review' => 'RAM dan storage bisa di-upgrade, fleksibel untuk kebutuhan future-proof.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'HeavyGamer', 'rating' => 4, 'review' => 'Beratnya 2.5kg, kurang cocok buat dibawa travel. Tapi layar 144Hz smooth banget!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'BudgetGamer', 'rating' => 4, 'review' => 'Harganya masih tinggi, tapi lebih worth daripada kompetitor sekelas.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'LinuxUser', 'rating' => 2, 'review' => 'Driver NVIDIA di Linux bermasalah, sering crash. Tidak cocok buat developer.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'StreamMaster', 'rating' => 4, 'review' => 'Lancar buat streaming di Twitch pakai OBS, tapi suhu CPU naik sampai 88°C. Perlu cooling pad ekstra.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'TravelGamer', 'rating' => 3, 'review' => 'Berat 2.5kg bikin pegal dibawa travel. Tapi layar 144Hz bikin game mulus!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'SoftwareHater', 'rating' => 4, 'review' => 'Bloatware Armoury Crate kadang lag. Untung bisa di-uninstall.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'FPSLover', 'rating' => 5, 'review' => 'Valorant di 300fps! Respons time layar 3ms bikin aiming lebih presisi.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'KeyboardFan', 'rating' => 5, 'review' => 'Key travel 1.8mm nyaman buat ngetik & gaming marathon.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'WarrantyUser', 'rating' => 4, 'review' => 'Garansi 2 tahun ASUS oke, tapi servis agak lama di kota kecil.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'VRUser', 'rating' => 4, 'review' => 'Support VR dengan Oculus Rift S lancar, tapi butuh ruang pendingin ekstra.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'BatteryOptimist', 'rating' => 3, 'review' => 'Baterai 4 jam kalau dipakai nonton film. Lumayan untuk laptop gaming!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'AestheticHater', 'rating' => 3, 'review' => 'Desain terlalu "gamer" dengan garis merah. Kurang profesional.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 1, 'responder_name' => 'DLSSFan', 'rating' => 5, 'review' => 'DLSS 2.0 di RTX 3060 bikin Red Dead 2 lancar di ultra 60fps!', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 2
            ['laptop_id' => 2, 'responder_name' => 'GraphicDesignPro', 'rating' => 5, 'review' => 'Warna layar 100% Adobe RGB akurat banget! Cocok buat editing 4K.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'WeightHater', 'rating' => 3, 'review' => 'Bobot 2.8kg terlalu berat buat mobile workstation. Tapi performa rendering cepat.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'StorageKing', 'rating' => 5, 'review' => '2TB SSD bikin lega! Tidak perlu khawatir kehabisan space untuk project besar.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'PriceShocker', 'rating' => 2, 'review' => 'Mahal banget! Harga segitu mending beli MacBook Pro.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'CreativePro', 'rating' => 5, 'review' => 'Color grading di DaVinci Resolve lancar, layar benar-benar presisi.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'HeatIssue', 'rating' => 4, 'review' => 'Saat render 3D, keyboard area agak panas. Tapi jarang thermal throttling.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port lengkap: 2x Thunderbolt 4, HDMI 2.1, cocok buat workstation!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'BatteryLifeOK', 'rating' => 4, 'review' => 'Baterai tahan 6 jam untuk editing foto, cukup untuk kerja mobile.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'KeyboardFan', 'rating' => 5, 'review' => 'Keyboard nyaman buat ngetik lama, key travel-nya pas.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker kurang bass, harus pakai headphone untuk editing audio.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'AnimatorPro', 'rating' => 5, 'review' => 'Render animasi 3D di Maya cuma 30 menit! Layar 4K 100% Adobe RGB memukau.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'TravelPhotog', 'rating' => 3, 'review' => 'Bobot 2.8kg kurang ideal buat fotografer mobile. Tapi performa editing kencang.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'CalibrationGeek', 'rating' => 5, 'review' => 'Factory-calibrated screen dengan delta-E <1! Presisi warna sempurna.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'PriceRealist', 'rating' => 4, 'review' => 'Mahal, tapi lebih worth buat profesional daripada MacBook Pro M1.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'BlenderUser', 'rating' => 5, 'review' => 'RTX 3070 + 32GB RAM ngerender Blender 2x lebih cepat!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'KeyboardHater', 'rating' => 3, 'review' => 'Keyboard agak keras buat ngetik lama. Butuh waktu adaptasi.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'LinuxEditor', 'rating' => 4, 'review' => 'Driver NVIDIA di Ubuntu stabil, tapi Optimus kurang smooth.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'HDRFilmmaker', 'rating' => 5, 'review' => 'Layar HDR 600 nits! Cocok buat color grading film HDR10.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'PortabilityHater', 'rating' => 2, 'review' => 'Kurang portabel buat dibawa ke lokasi shooting. Lebih cocok di studio.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 2, 'responder_name' => 'SilentEditor', 'rating' => 4, 'review' => 'Kipas hampir nggak berisik saat edit foto. Tapi panas saat render video.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 3
            ['laptop_id' => 3, 'responder_name' => 'Student123', 'rating' => 4, 'review' => 'Ringan dan baterai tahan lama (8 jam). Cocok buat kuliah online.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'GamerFail', 'rating' => 2, 'review' => 'GPU Intel Iris cuma kuat buat game 2D. Jangan harap main Valorant di high.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'BudgetBuyer', 'rating' => 5, 'review' => 'Harga 8 jutaan worth it untuk kerja kantor & nonton Netflix.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'PlasticHater', 'rating' => 3, 'review' => 'Bodi plastik murahan, layar flexing kalau dibuka satu tangan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'Traveler', 'rating' => 5, 'review' => 'Berat cuma 1.8kg, mudah dibawa ke mana-mana. SSD bikin startup cepat.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'UpgradeFail', 'rating' => 2, 'review' => 'RAM soldered, tidak bisa di-upgrade. Pilihan storage juga terbatas.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'OfficeUser', 'rating' => 4, 'review' => 'Windows 11 lancar buat Excel & Zoom meeting. Webcam 720p cukup standar.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'ScreenHater', 'rating' => 3, 'review' => 'Layar cuma 250 nits, susah dipakai di luar ruangan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'KeyboardLover', 'rating' => 4, 'review' => 'Layout keyboard nyaman, ada numeric pad. Touchpad responsif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'AudioLover', 'rating' => 5, 'review' => 'Speaker dengan SonicMaster jernih banget buat laptop segini!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'EduCreator', 'rating' => 4, 'review' => 'Cocok buat edit video sederhana di CapCut. GPU Intel Iris cukup buat 1080p.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'BatterySaver', 'rating' => 5, 'review' => 'Baterai tahan 9 jam kalau dipakai Microsoft Teams + Chrome.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'PlasticLover', 'rating' => 3, 'review' => 'Bodi plastik ringan, tapi mudah baret. Harga 8 juta masih oke.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'MultitaskHater', 'rating' => 2, 'review' => 'RAM 8GB kurang kalau buka 20 tab Chrome + Zoom. Sering freeze.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'TravelStudent', 'rating' => 5, 'review' => 'Berat 1.8kg mudah dibawa ke kampus. SSD bikin startup cepat!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'AudioEditor', 'rating' => 3, 'review' => 'Speaker kurang bass buat edit audio. Harus pakai headphone eksternal.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'WebcamFan', 'rating' => 4, 'review' => 'Webcam 720p cukup buat kuliah online. Ada noise reduction basic.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'LinuxNewbie', 'rating' => 5, 'review' => 'Lancar pakai Zorin OS. Driver Intel kompatibel tanpa masalah.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'DesignHater', 'rating' => 3, 'review' => 'Desain terlalu biasa. ASUS harusnya kasih warna lebih menarik.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 3, 'responder_name' => 'BudgetHero', 'rating' => 5, 'review' => 'Harga terjangkau buat spek ini! Siswa bisa beli tanpa ngutang.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 4
            ['laptop_id' => 4, 'responder_name' => 'BusinessUser', 'rating' => 4, 'review' => 'Ringan (1.1kg) dan baterai tahan 10 jam! Cocok buat rapat seharian. Sayang performa terbatas buat multitasking berat.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'LightweightFan', 'rating' => 5, 'review' => 'Portabel banget! Layar 14" tajam, tapi RAM 8GB kurang untuk Photoshop.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'DurabilityTester', 'rating' => 5, 'review' => 'Bodi magnesium alloy anti-gores. Tahan banting, tapi port USB-C cuma 1.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'TravelerPro', 'rating' => 4, 'review' => 'Baterai awet, charger-nya kecil. Layar 300 nits cukup terang di outdoor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'OfficeWorker', 'rating' => 4, 'review' => 'Keyboard nyaman + fingerprint sensor. GPU Intel UHD kurang untuk video call 4K.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'WebcamUser', 'rating' => 3, 'review' => 'Webcam 720p kurang tajam, tapi privacy shutter-nya berguna.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'SecurityMind', 'rating' => 5, 'review' => 'Fitur keamanan lengkap: TPM 2.0 + Windows Hello. Ideal untuk data sensitif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'StudentPlus', 'rating' => 4, 'review' => 'Cocok buat kuliah, tapi speaker agak kecil. SSD 512GB cukup untuk tugas.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'DesignHater', 'rating' => 3, 'review' => 'Desain terlalu polos. Minimalis sih, tapi kurang menarik.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'LinuxUser', 'rating' => 5, 'review' => 'Kompatibel dengan Ubuntu. Driver Wi-Fi & Bluetooth stabil.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'CEOOnTheGo', 'rating' => 5, 'review' => 'Bodi magnesium alloy premium & berat 1.1kg! Perfect buat eksekutif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'MultitaskPro', 'rating' => 4, 'review' => 'RAM 8GB cukup buat 10 tab Excel + PowerPoint. SSD bikin responsif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'SecurityGuard', 'rating' => 5, 'review' => 'Fitur TPM 2.0 + fingerprint sensor. Aman buat data rahasia perusahaan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'ScreenRealist', 'rating' => 4, 'review' => 'Layar 14" 300 nits cukup terang di ruang meeting. Warna natural.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'TravelerCEO', 'rating' => 5, 'review' => 'Baterai 10 jam tahan seharian meeting di bandara. Charger kecil praktis!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'GamerFail', 'rating' => 1, 'review' => 'Intel UHD nggak kuat main game apa pun. Tapi ya emang buat kerja sih.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'LinuxExecutive', 'rating' => 5, 'review' => 'Kompatibel dengan Fedora Workstation. Driver Wi-Fi stabil.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'PortHater', 'rating' => 3, 'review' => 'Cuma 2 port USB-C. Harus pakai dongle buat HDMI & Ethernet.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'KeyboardMaster', 'rating' => 5, 'review' => 'Keyboard ergonomis dengan key travel 1.5mm. Ngetik 8 jam nggak pegal!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 4, 'responder_name' => 'PriceDebater', 'rating' => 4, 'review' => '12 juta agak mahal, tapi build quality & garansi 3 tahun worth it.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 5
            ['laptop_id' => 5, 'responder_name' => 'ProGamer', 'rating' => 5, 'review' => 'RTX 3060 + i7-12700H ngebut! Main COD: Warzone di 1440p ultra lancar.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'HeatWarrior', 'rating' => 4, 'review' => 'Suhu CPU bisa 95°C saat gaming. Paksa pakai cooling pad ekstra.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'DisplayGeek', 'rating' => 5, 'review' => 'Layar 165Hz IPS warna tajam! Responsif buat FPS kompetitif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'BatteryHater', 'rating' => 2, 'review' => 'Baterai cuma 3 jam buat nonton film. Tapi ya emang laptop gaming.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'UpgradeMaster', 'rating' => 5, 'review' => 'RAM & SSD bisa di-upgrade sendiri. Ada slot NVMe kedua!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'NoiseComplaint', 'rating' => 3, 'review' => 'Kipas berisik banget di mode Turbo. Tapi performa emang gila.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'RGBLover', 'rating' => 4, 'review' => 'Keyboard RGB keren, tapi software PredatorSense sering error.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'PortableGamer', 'rating' => 4, 'review' => 'Berat 2.6kg, masih bisa masuk tas ransel. Layar anti-silau oke.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'BudgetFinder', 'rating' => 5, 'review' => 'Harga 17 jutaan worth untuk spek ini! RTX 3060 jarang di harga segini.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'LinuxGamer', 'rating' => 2, 'review' => 'Driver NVIDIA di Arch Linux bermasalah. Stick ke Windows aja.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'OverclockMaster', 'rating' => 5, 'review' => 'i7-12700H bisa di-overclock sampai 4.7GHz! Performa ngebut buat render dan gaming.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'NoiseSensitive', 'rating' => 2, 'review' => 'Kipas berisik seperti jet engine. Harus pakai headphone noise-canceling!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'VRReady', 'rating' => 4, 'review' => 'Support VR Oculus Rift S lancar, tapi suhu naik cepat. Butuh cooling pad.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'BatteryOptimist', 'rating' => 3, 'review' => 'Baterai 4 jam untuk nonton film. Lumayan untuk laptop gaming.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'AestheticFan', 'rating' => 4, 'review' => 'Desain agresif dengan LED biru. Cocok buat gamers yang suka gaya.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'PortHater', 'rating' => 3, 'review' => 'USB-C cuma 1 port. Kurang untuk peripheral gaming.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'BudgetWarrior', 'rating' => 5, 'review' => 'Harga 17 jutaan untuk RTX 3060? Deal of the year!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'ThermalModder', 'rating' => 4, 'review' => 'Undervolt CPU bisa turunkan suhu 10°C. Performa tetap stabil!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'LinuxGamer', 'rating' => 2, 'review' => 'Driver NVIDIA di Arch Linux bermasalah. Paksa dual-boot Windows.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 5, 'responder_name' => 'KeyboardWarrior', 'rating' => 5, 'review' => 'Key travel 2mm nyaman buat ngetik & gaming. RGB-nya customizable!', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 6
            ['laptop_id' => 6, 'responder_name' => '3DArtist', 'rating' => 5, 'review' => 'RTX 3080 + 32GB RAM ngerender Blender 3x lebih cepat! Layar 4K presisi.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'WeightHater', 'rating' => 3, 'review' => 'Bobot 2.7kg kurang cocok buat mobile. Tapi layarnya spektakuler.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'ColorSensitive', 'rating' => 5, 'review' => 'Delta-E <1! Cocok buat color grading profesional di Premiere Pro.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'PriceShocker', 'rating' => 2, 'review' => 'Mahal banget! Tapi ya targetnya profesional kreatif sih.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'SilentWorker', 'rating' => 5, 'review' => 'Kipas hampir nggak berisik saat editing foto. Thermal design keren!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'StorageKing', 'rating' => 5, 'review' => '2TB SSD bikin lega! Bisa simpan 100+ project tanpa khawatir.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'BatteryLifeOK', 'rating' => 4, 'review' => 'Baterai tahan 5 jam buat Photoshop. Cukup untuk kerja mobile.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port Thunderbolt 4 & HDMI 2.1 lengkap! Konek dual monitor gampang.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker datar, harus pakai headphone eksternal untuk mixing audio.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'DesignAdmirer', 'rating' => 5, 'review' => 'Desain minimalis elegan! Beda dari laptop gaming yang norak.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => '4KEditor', 'rating' => 5, 'review' => 'RTX 3080 ngerender timeline 4K di Premiere Pro tanpa lag. Layar 4K HDR wow!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'TravelHater', 'rating' => 3, 'review' => 'Berat 2.7kg bikin pegal dibawa ke lokasi shooting. Tapi layarnya spektakuler.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'SilentCreator', 'rating' => 5, 'review' => 'Kipas nggak berisik saat rendering foto. Thermal design Acer keren!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'PriceRealist', 'rating' => 4, 'review' => 'Mahal, tapi lebih worth buat studio profesional daripada Mac Pro.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'ColorPerfectionist', 'rating' => 5, 'review' => 'Factory calibration delta-E <1! Akurat buat color grading film.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'AudioEditor', 'rating' => 3, 'review' => 'Speaker datar, harus pakai headphone studio eksternal.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'LinuxPro', 'rating' => 5, 'review' => 'Driver NVIDIA Studio di Ubuntu stabil. Bisa CUDA acceleration!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'BatterySaver', 'rating' => 4, 'review' => 'Baterai tahan 6 jam untuk editing foto. Cukup buat kerja mobile.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Thunderbolt 4 & HDMI 2.1 lengkap! Konek ke 2 monitor 4K sekaligus.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 6, 'responder_name' => 'DesignHater', 'rating' => 4, 'review' => 'Desain terlalu polos untuk harga segini. Tapi performa memang prioritas.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 7
            ['laptop_id' => 7, 'responder_name' => 'BudgetStudent', 'rating' => 4, 'review' => 'Ringan & baterai tahan 7 jam! Cocok buat kuliah, tapi RAM 8GB kadang lag buka banyak tab.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'CasualGamer', 'rating' => 3, 'review' => 'Radeon Vega 7 cuma kuat main Dota 2 di low settings. Tapi harga 7 jutaan oke lah.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'OfficeWorker', 'rating' => 5, 'review' => 'SSD 512GB bikin Windows 11 cepat! Keyboard nyaman buat ngetik laporan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'ScreenHater', 'rating' => 3, 'review' => 'Layar 250 nits redup di ruangan terang. Warna agak kusam buat editing foto.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'Traveler', 'rating' => 4, 'review' => 'Berat 1.6kg mudah dibawa, tapi bodi plastik rawan baret. Harga sesuai performa.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'UpgradeLover', 'rating' => 4, 'review' => 'Bisa tambah RAM sampai 16GB dan ganti SSD. Fleksibel buat upgrade murah.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'WebcamUser', 'rating' => 2, 'review' => 'Webcam 720p buram banget! Zoom meeting harus pakai eksternal cam.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'BatteryFan', 'rating' => 5, 'review' => 'Baterai awet 8 jam buat nonton YouTube. Charger kecil praktis dibawa.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker cempreng, bass kurang. Harus pakai headphone buat denger musik.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'LinuxUser', 'rating' => 5, 'review' => 'Lancar pakai Ubuntu. Driver AMD Radeon kompatibel sempurna!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'StudentLife', 'rating' => 4, 'review' => 'Ringan & baterai tahan 8 jam. Cocok buat kuliah online + tugas ringan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'GamerDisappointed', 'rating' => 2, 'review' => 'Radeon Vega 7 cuma kuat main game 2D. Jangan harap main Genshin Impact!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'MultitaskHater', 'rating' => 3, 'review' => 'RAM 8GB kurang kalau buka Zoom + 15 tab Chrome. Sering lag.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'BudgetHero', 'rating' => 5, 'review' => 'Harga 7 jutaan worth untuk SSD 512GB & build quality cukup solid.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'TravelStudent', 'rating' => 4, 'review' => 'Berat 1.6kg mudah dibawa, tapi bodi plastik mudah baret.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'UpgradeGeek', 'rating' => 4, 'review' => 'Bisa tambah RAM sampai 16GB & SSD 1TB. Fleksibel untuk upgrade murah.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'WebcamUser', 'rating' => 3, 'review' => 'Webcam 720p buram, tapi ada privacy shutter. Aman buat Zoom meeting.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'LinuxStarter', 'rating' => 5, 'review' => 'Lancar pakai Linux Mint. Driver AMD Radeon kompatibel sempurna!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'AudioLover', 'rating' => 3, 'review' => 'Speaker cempreng, bass kurang. Harus pakai headphone buat denger musik.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 7, 'responder_name' => 'DesignFan', 'rating' => 4, 'review' => 'Desain minimalis dengan bezel tipis. Layar 15.6" nyaman buat ngerjakan tugas.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 8
            ['laptop_id' => 8, 'responder_name' => 'BusinessNomad', 'rating' => 5, 'review' => 'Bodi magnesium alloy tahan banting! Baterai 12 jam untuk kerja lapangan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'SecurityPro', 'rating' => 5, 'review' => 'Fingerprint + TPM 2.0 aman buat data kantor. Layar anti-silau oke di outdoor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'WeightLover', 'rating' => 4, 'review' => 'Ringan 1.2kg, port USB-A & HDMI lengkap. Tapi harganya agak mahal.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'PerformanceHater', 'rating' => 3, 'review' => 'Intel Iris Xe kurang untuk render video 4K. Cocoknya buat kerja kantor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'TravelerPro', 'rating' => 5, 'review' => 'Tahan air & debu! Perfect buat kerja di lapangan atau kafe berdebu.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'AudioDisappointed', 'rating' => 2, 'review' => 'Speaker kecil & suara pecah. Meeting online harus pakai headset.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'UpgradeFail', 'rating' => 2, 'review' => 'RAM soldered, tidak bisa di-upgrade. Storage juga fixed 512GB.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'DesignLover', 'rating' => 4, 'review' => 'Desain profesional & minimalis. Cocok buat eksekutif muda.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'LinuxGeek', 'rating' => 5, 'review' => 'Driver Intel kompatibel sempurna dengan Fedora. No issue!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'PriceComplaint', 'rating' => 3, 'review' => '11 juta buat spek ini? Competitor seperti ThinkPad lebih worth.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'BusinessNomad', 'rating' => 5, 'review' => 'Bodi magnesium alloy tahan banting & berat 1.2kg! Perfect buat business trip.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'SecurityPro', 'rating' => 5, 'review' => 'Fingerprint sensor + TPM 2.0. Data perusahaan aman dari peretas!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'PerformanceHater', 'rating' => 3, 'review' => 'Intel Iris Xe kurang untuk render video 1080p. Cocok hanya untuk Office.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'BatteryLife', 'rating' => 4, 'review' => 'Baterai tahan 10 jam untuk Excel & browsing. Charger kecil praktis!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port lengkap: HDMI, USB-C, LAN. Tidak perlu repot bawa dongle!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'AudioHater', 'rating' => 2, 'review' => 'Speaker suara pecah. Meeting online harus pakai headset eksternal.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'LinuxGeek', 'rating' => 5, 'review' => 'Kompatibel dengan Fedora. Driver Intel stabil tanpa bug.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'UpgradeFail', 'rating' => 2, 'review' => 'RAM soldered & storage fixed. Tidak bisa di-upgrade sama sekali!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'DesignAdmirer', 'rating' => 4, 'review' => 'Desain profesional dengan finishing anti-sidik jari. Cocok buat meeting klien.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 8, 'responder_name' => 'PriceDebate', 'rating' => 4, 'review' => '11 juta agak mahal, tapi garansi 3 tahun & durability worth it.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 9
            ['laptop_id' => 9, 'responder_name' => 'ProGamer', 'rating' => 5, 'review' => 'RTX 3070 + Ryzen 7 6800H ngebut! Main Elden Ring di 1440p ultra smooth. Layar 165Hz warna tajam!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'HeatWarner', 'rating' => 4, 'review' => 'Suhu GPU 85°C saat gaming marathon. Perlu undervolt biar stabil.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port lengkap: USB-C PD, HDMI 2.1, LAN. Bisa colok dual monitor + charger pakai 1 port.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'BatteryHater', 'rating' => 2, 'review' => 'Baterai cuma 2 jam buat gaming. Tapi ya wajar buat laptop sekuat ini.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'RGBMaster', 'rating' => 4, 'review' => 'Keyboard RGB keren, tapi software Lenovo Vantage kadang lag.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'UpgradeGeek', 'rating' => 5, 'review' => 'RAM & SSD bisa di-upgrade sendiri. Ada slot NVMe kedua buat tambah storage!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'WeightHater', 'rating' => 3, 'review' => 'Berat 2.5kg, kurang portabel. Tapi layar 16" 16:10 bikin produktif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'LinuxGamer', 'rating' => 3, 'review' => 'NVIDIA Optimus bikin repot di Ubuntu. Stick ke Windows buat gaming.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'BudgetGamer', 'rating' => 5, 'review' => 'Harga 21 juta worth it! Performa setara laptop 25 juta dari kompetitor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'FanNoise', 'rating' => 4, 'review' => 'Kipas berisik di mode performance, tapi dinginnya konsisten.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'RayTracingFan', 'rating' => 5, 'review' => 'RTX 3070 + DLSS 2.0 bikin Cyberpunk 2077 di 1440p ultra 60fps! Ray tracing keren tapi suhu GPU tembus 80°C.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'PortableWarrior', 'rating' => 4, 'review' => 'Berat 2.5kg cukup berat, tapi layar 16" 165Hz bikin game immersive!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'BloatwareHater', 'rating' => 3, 'review' => 'Lenovo Vantage banyak notifikasi mengganggu. Untung bisa di-uninstall.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'ThermalMaster', 'rating' => 4, 'review' => 'Mode Quiet bisa turunkan suhu 10°C, tapi FPS turun 20%. Worth untuk kerja non-gaming.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'KeyboardLover', 'rating' => 5, 'review' => 'Keyboard mekanis 1.5mm key travel! Nyaman buat ngetik & gaming marathon.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'LinuxGamer', 'rating' => 2, 'review' => 'NVIDIA Optimus bikin sakit kepala di Ubuntu. Paksa dual-boot Windows.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'BatteryRealist', 'rating' => 3, 'review' => 'Baterai 3 jam buat gaming, 6 jam buat nonton film. Standar laptop gaming.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'UpgradeGeek', 'rating' => 5, 'review' => 'Bisa pasang 2x SSD NVMe + 64GB RAM. Future-proof banget!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'AestheticHater', 'rating' => 4, 'review' => 'Desain agresif dengan logo Legion glow. Kurang cocok buat kantor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 9, 'responder_name' => 'FPSEnthusiast', 'rating' => 5, 'review' => 'Valorant 300fps di 1440p! Layar 165Hz bikin aiming lebih responsif.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 10
            ['laptop_id' => 10, 'responder_name' => 'VideoEditorPro', 'rating' => 5, 'review' => '32GB RAM + RTX 3060 ngerender 4K di Premiere Pro cuma 20 menit! Layar 4K HDR memukau.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'WeightComplaint', 'rating' => 3, 'review' => 'Berat 2.1kg untuk workstation. Tapi keyboard ThinkPad terbaik di kelasnya!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'ColorAccuracy', 'rating' => 5, 'review' => '100% Adobe RGB akurat! Cocok buat color grading film indie.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'PriceShocker', 'rating' => 2, 'review' => 'Mahal banget! Tapi ya targetnya profesional yang butuh performa mobile.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'BatteryLife', 'rating' => 4, 'review' => 'Baterai tahan 6 jam buat editing foto. Cukup untuk kerja di kafe.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'DurabilityFan', 'rating' => 5, 'review' => 'Bodi carbon fiber tahan benturan. Sudah jatuh 2x masih normal!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'HeatIssue', 'rating' => 4, 'review' => 'Saat render 3D, area WASD agak hangat. Tapi nggak thermal throttle.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'LinuxUser', 'rating' => 5, 'review' => 'Driver NVIDIA + Ubuntu kompatibel sempurna. Bisa CUDA acceleration!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker datar, harus pakai headphone untuk editing audio.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'TravelWorkstation', 'rating' => 5, 'review' => 'Port Thunderbolt 4 + SD card reader. Perfect buat fotografer traveling!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => '4KEditor', 'rating' => 5, 'review' => 'Layar 4K HDR 600 nits! Warna akurat buat grading film di DaVinci Resolve.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'HeatComplaint', 'rating' => 4, 'review' => 'Suhu CPU 85°C saat render 3D, tapi nggak thermal throttle. Kipas cukup efisien.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'TravelPhotog', 'rating' => 3, 'review' => 'Berat 2.1kg kurang ideal buat dibawa ke lokasi shooting. Tapi performa worth!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'LinuxPro', 'rating' => 5, 'review' => 'Driver NVIDIA Studio di Fedora stabil. Bisa CUDA acceleration untuk Blender!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'BatterySaver', 'rating' => 4, 'review' => 'Baterai tahan 5 jam buat edit foto. Cukup buat mobile kerja di kafe.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'KeyboardMaster', 'rating' => 5, 'review' => 'Keyboard ThinkPad legendaris! Key travel 1.8mm nyaman buat ngetik 8 jam.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'PriceDebate', 'rating' => 3, 'review' => 'Mahal banget, tapi layar & performa setara workstation desktop.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'DurabilityFan', 'rating' => 5, 'review' => 'Bodi carbon fiber tahan benturan. Sudah terjatuh 3x masih normal!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker datar, harus pakai headphone studio untuk mixing audio.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 10, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => '2x Thunderbolt 4 + SD card reader. Perfect buat fotografer profesional!', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 11
            ['laptop_id' => 11, 'responder_name' => 'StudentUser', 'rating' => 4, 'review' => 'Harga 8 juta ringan buat tugas. Baterai tahan 7 jam, cocok buat kampus.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'GamerDisappointed', 'rating' => 2, 'review' => 'Radeon Vega 7 cuma kuat buat Minecraft. Jangan harap main AAA games.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'OfficeLover', 'rating' => 5, 'review' => 'SSD 512GB bikin startup cepat. Windows 11 lancar buat Zoom + Office.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'PlasticHater', 'rating' => 3, 'review' => 'Bodi plastik murahan, layar goyah kalau disentuh. Tapi murah sih.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'TravelStudent', 'rating' => 5, 'review' => 'Berat 1.4kg, mudah dibawa. Layar anti-silau cukup buat ruang kelas.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'UpgradeFail', 'rating' => 2, 'review' => 'RAM soldered, storage cuma 1 slot. Tidak fleksibel untuk upgrade.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'WebcamUser', 'rating' => 3, 'review' => 'Webcam 720p buram, tapi privacy shutter membantu.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'BatteryFan', 'rating' => 4, 'review' => 'Baterai awet, tapi charger bulky. Layar 14" cukup untuk multitasking.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'AudioLover', 'rating' => 4, 'review' => 'Speaker jernih buat kelas entry-level. Bass kurang, tapi suara jelas.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'LinuxStarter', 'rating' => 5, 'review' => 'Kompatibel dengan Linux Mint. Driver AMD stabil tanpa issue!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'StudentLife', 'rating' => 4, 'review' => 'Harga 8 juta cocok buat tugas kuliah. Baterai tahan 7 jam!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'GamerDisappointed', 'rating' => 2, 'review' => 'Radeon Vega 7 cuma kuat main game 2D. Genshin Impact low settings pun lag.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'OfficeUser', 'rating' => 5, 'review' => 'SSD 512GB bikin Windows 11 cepat. Ringan buat Zoom + Microsoft Office.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'BuildHater', 'rating' => 3, 'review' => 'Bodi plastik mudah baret. Layar flexing kalau dibuka satu tangan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'TravelStudent', 'rating' => 5, 'review' => 'Berat 1.4kg mudah dibawa ke kampus. Charger kecil praktis!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'UpgradeFail', 'rating' => 1, 'review' => 'RAM soldered & storage fixed. Tidak bisa di-upgrade sama sekali!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'WebcamUser', 'rating' => 3, 'review' => 'Webcam 720p buram, tapi ada privacy shutter buat keamanan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'LinuxNewbie', 'rating' => 5, 'review' => 'Lancar pakai Zorin OS. Driver AMD kompatibel tanpa masalah.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'AudioLover', 'rating' => 3, 'review' => 'Speaker suara kecil, bass kurang. Tapi jernih buat podcast.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 11, 'responder_name' => 'DesignFan', 'rating' => 4, 'review' => 'Desain minimalis dengan bezel tipis. Layar 14" nyaman buat multitasking.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 12
            ['laptop_id' => 12, 'responder_name' => 'OfficeWorker', 'rating' => 4, 'review' => 'Ringan & baterai tahan 9 jam. Cocok buat meeting seharian. Webcam 1080p tajam!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'PerformanceUser', 'rating' => 3, 'review' => 'Intel i5-1135G7 kurang buat multitasking 20+ tab Chrome. Tapi SSD membantu.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'DurabilityFan', 'rating' => 5, 'review' => 'Bodi aluminium anti-fingerprint. Tahan gores & tumpahan kopi.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port lengkap: HDMI, USB-C, Ethernet. Tidak perlu dongle!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'ScreenHater', 'rating' => 3, 'review' => 'Layar 250 nits redup di outdoor. Tapi di ruangan AC cukup terang.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'SecurityMind', 'rating' => 5, 'review' => 'Fingerprint sensor + webcam shutter. Aman untuk data perusahaan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'UpgradeMaster', 'rating' => 4, 'review' => 'Bisa tambah RAM sampai 40GB & SSD 1TB. Fleksibel untuk upgrade.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'DesignLover', 'rating' => 4, 'review' => 'Desain profesional dengan logo ThinkBook elegan. Cocok buat eksekutif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker kurang bass, meeting online harus pakai headset.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'PriceComplaint', 'rating' => 4, 'review' => '10.5 juta agak mahal, tapi build quality & garansi 3 tahun worth it.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'OfficePro', 'rating' => 4, 'review' => 'Bodi aluminium kokoh & ringan. Cocok buat meeting seharian.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'MultitaskHater', 'rating' => 3, 'review' => 'RAM 8GB kurang buka 20 tab Chrome + Excel. Upgrade ke 16GB wajib!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'SecurityGuard', 'rating' => 5, 'review' => 'Fingerprint sensor + TPM 2.0. Data kantor aman dari kebocoran.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port lengkap: HDMI, USB-C, LAN. Tidak perlu dongle untuk presentasi!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'BatteryLife', 'rating' => 4, 'review' => 'Baterai tahan 8 jam buat kerja kantor. Charger cepat 65W praktis.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'ScreenRealist', 'rating' => 3, 'review' => 'Layar 250 nits redup di outdoor. Tapi di ruangan cukup terang.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'UpgradeMaster', 'rating' => 4, 'review' => 'Bisa tambah RAM sampai 40GB & SSD 1TB. Fleksibel untuk kebutuhan kantor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'DesignAdmirer', 'rating' => 5, 'review' => 'Desain profesional dengan logo ThinkBook elegan. Cocok buat eksekutif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'AudioHater', 'rating' => 2, 'review' => 'Speaker suara pecah. Meeting online harus pakai headset eksternal.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 12, 'responder_name' => 'PriceDebate', 'rating' => 4, 'review' => '10.5 juta agak mahal, tapi garansi 3 tahun & durability worth it.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 13
            ['laptop_id' => 13, 'responder_name' => 'ProGamer', 'rating' => 5, 'review' => 'RTX 3060 + Ryzen 7 5800H combo kencang! Main Apex Legends di 144Hz smooth banget. Layar anti-ghosting oke!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'HeatComplaint', 'rating' => 3, 'review' => 'Suhu CPU tembus 95°C saat gaming 3 jam. Wajib pakai cooling pad ekstra.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'BatteryHater', 'rating' => 2, 'review' => 'Baterai cuma 1.5 jam buat gaming. Tapi ya emang laptop gaming sih...', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port lengkap: MiniDP, HDMI, USB-C. Bisa colok 3 monitor sekaligus!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'RGBEnthusiast', 'rating' => 4, 'review' => 'Keyboard RGB keren, tapi software Omen Command Center sering crash.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'UpgradeMaster', 'rating' => 5, 'review' => 'RAM & SSD bisa di-upgrade sendiri. Ada slot NVMe tambahan!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'WeightHater', 'rating' => 3, 'review' => 'Berat 2.3kg, kurang portabel. Tapi layar 15.6" 144Hz worth it!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'NoiseComplaint', 'rating' => 4, 'review' => 'Kipas berisik di mode turbo, tapi performa tetap stabil.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'BudgetGamer', 'rating' => 4, 'review' => 'Harga 18.5 juta kompetitif. RTX 3060 di HP jarang di harga segini.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'LinuxGamer', 'rating' => 2, 'review' => 'Driver NVIDIA di Arch Linux bermasalah. Gaming paksa pakai Windows.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'ProGamer', 'rating' => 5, 'review' => 'Ryzen 7 5800H + RTX 3060 combo mantap! Main Warzone di 1440p ultra lancar 80fps. Layar 144Hz smooth!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'HeatWarner', 'rating' => 3, 'review' => 'Suhu CPU tembus 95°C saat gaming 2 jam. Wajib pakai cooling pad ekstra.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port lengkap: MiniDP, HDMI 2.1, USB-C. Bisa konek 3 monitor sekaligus!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'BatteryHater', 'rating' => 2, 'review' => 'Baterai cuma 2 jam buat gaming. Tapi ya emang laptop gaming sih...', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'RGBEnthusiast', 'rating' => 4, 'review' => 'Keyboard RGB keren, tapi software Omen Command Center sering crash.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'UpgradeMaster', 'rating' => 5, 'review' => 'Bisa upgrade RAM ke 32GB & tambah SSD 1TB. Future-proof!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'NoiseComplaint', 'rating' => 3, 'review' => 'Kipas berisik banget di mode Turbo. Tapi performa emang gila.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'LinuxGamer', 'rating' => 2, 'review' => 'Driver NVIDIA di Arch Linux bermasalah. Gaming paksa pakai Windows.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'AestheticFan', 'rating' => 4, 'review' => 'Desain stealthy dengan logo Omen glow. Cocok buat gamers low-key.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 13, 'responder_name' => 'BudgetFinder', 'rating' => 5, 'review' => 'Harga 18.5 juta worth untuk RTX 3060! Lebih murah dari kompetitor.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 14
            ['laptop_id' => 14, 'responder_name' => '3DArtist', 'rating' => 5, 'review' => 'Xeon + RTX 4000 ngerender Blender 2x lebih cepat! Layar 4K 600 nits spektakuler.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'WeightHater', 'rating' => 2, 'review' => 'Bobot 3kg terlalu berat buat mobile workstation. Tapi performa setara desktop!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'ColorSensitive', 'rating' => 5, 'review' => 'Layar 100% DCI-P3 akurat untuk color grading film. Delta-E < 1!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'PriceShocker', 'rating' => 1, 'review' => '45 juta? Mahal banget! Tapi ya targetnya studio profesional sih.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'StorageKing', 'rating' => 5, 'review' => '2TB SSD + slot NVMe tambahan. Bisa simpan 100+ project 8K!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'DurabilityFan', 'rating' => 5, 'review' => 'Bodi aluminium MIL-STD tested. Tahan jatuh dari meja!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'HeatIssue', 'rating' => 4, 'review' => 'Saat render 3D, keyboard area hangat. Tapi nggak thermal throttle.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'LinuxPro', 'rating' => 5, 'review' => 'Driver NVIDIA Studio + Ubuntu kompatibel sempurna. CUDA acceleration lancar!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker datar, harus pakai headphone eksternal untuk mixing audio.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => '4x Thunderbolt 4 + LAN port. Konektivitas workstation level dewa!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => '3DArtistPro', 'rating' => 5, 'review' => 'Xeon W-10885M + RTX 4000 ngerender Blender 3x lebih cepat! Layar 4K 600 nits spektakuler.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'WeightHater', 'rating' => 2, 'review' => 'Bobot 3kg terlalu berat buat mobile workstation. Performa setara desktop!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'ColorSensitive', 'rating' => 5, 'review' => '100% DCI-P3 & factory calibration. Warna akurat untuk film 4K HDR!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'PriceShocker', 'rating' => 1, 'review' => '45 juta? Tapi ya targetnya studio profesional yang butuh presisi.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'StorageKing', 'rating' => 5, 'review' => '2TB SSD + slot NVMe tambahan. Bisa simpan 100+ project 8K!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'HeatIssue', 'rating' => 4, 'review' => 'Saat render 3D, keyboard hangat. Tapi jarang thermal throttle.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'LinuxPro', 'rating' => 5, 'review' => 'Driver NVIDIA Studio di Ubuntu stabil. Bisa CUDA acceleration!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'BatteryLife', 'rating' => 3, 'review' => 'Baterai 4 jam buat editing foto. Tapi ya workstation mobile sih...', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => '4x Thunderbolt 4 + LAN port. Konektivitas workstation level dewa!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 14, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker datar. Harus pakai headphone studio untuk mixing audio.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 15
            ['laptop_id' => 15, 'responder_name' => 'StudentLife', 'rating' => 4, 'review' => 'Harga 6 juta cocok buat tugas kuliah. Baterai tahan 8 jam!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'GamerDisappointed', 'rating' => 1, 'review' => 'Intel UHD cuma kuat main Among Us. Jangan harap game AAA!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'OfficeUser', 'rating' => 4, 'review' => 'Ringan 1.5kg & SSD 256GB. Cukup buat Word & Zoom meeting.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'BuildQualityHater', 'rating' => 2, 'review' => 'Bodi plastik tipis, layar flexing kalau dibuka kasar.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'TravelStudent', 'rating' => 5, 'review' => 'Mudah dibawa ke kampus. Layar 14" anti-silau cukup terang.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'UpgradeFail', 'rating' => 2, 'review' => 'RAM 4GB soldered, storage cuma 256GB. Tidak bisa di-upgrade!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'WebcamHater', 'rating' => 3, 'review' => 'Webcam 720p buram, tapi privacy shutter membantu.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'BatteryFan', 'rating' => 5, 'review' => 'Baterai hemat, tahan seharian kuliah offline.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'AudioLover', 'rating' => 3, 'review' => 'Speaker kecil, bass kurang. Tapi suara jernih untuk podcast.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'LinuxNewbie', 'rating' => 4, 'review' => 'Lancar pakai Linux Mint. Driver Intel kompatibel tanpa masalah.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'StudentLife', 'rating' => 4, 'review' => 'Harga 6 juta cocok buat tugas kuliah. Baterai tahan 8 jam!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'GamerDisappointed', 'rating' => 1, 'review' => 'Intel UHD cuma kuat main Among Us. Jangan harap game AAA!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'OfficeUser', 'rating' => 4, 'review' => 'Ringan 1.5kg & SSD 256GB. Cukup buat Zoom meeting & ngetik laporan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'BuildQualityHater', 'rating' => 2, 'review' => 'Bodi plastik tipis, layar goyah kalau dibuka kasar.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'TravelStudent', 'rating' => 5, 'review' => 'Mudah dibawa ke kampus. Layar anti-silau cukup terang di ruang kelas.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'UpgradeFail', 'rating' => 2, 'review' => 'RAM 4GB soldered & storage fixed. Tidak bisa di-upgrade!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'WebcamUser', 'rating' => 3, 'review' => 'Webcam 720p buram, tapi privacy shutter membantu.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'LinuxNewbie', 'rating' => 5, 'review' => 'Lancar pakai Linux Mint. Driver Intel kompatibel tanpa masalah.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'AudioLover', 'rating' => 3, 'review' => 'Speaker kecil, bass kurang. Tapi suara jernih untuk podcast.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 15, 'responder_name' => 'BudgetHero', 'rating' => 4, 'review' => 'Harga terjangkau buat siswa. SSD 256GB lebih cepat daripada HDD!', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 16
            ['laptop_id' => 16, 'responder_name' => 'OfficePro', 'rating' => 4, 'review' => 'Bodi kokoh & keyboard nyaman. Cocok buat kerja 8 jam sehari.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'PerformanceHater', 'rating' => 3, 'review' => 'Intel i5-1135G7 kurang buat multitasking 10+ aplikasi. RAM 8GB pas-pasan.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port lengkap: USB-C, HDMI, LAN. Tidak perlu dongle untuk presentasi!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'SecurityMind', 'rating' => 5, 'review' => 'Fitur keamanan HP Sure Start + fingerprint sensor. Aman buat data kantor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'ScreenDisappointed', 'rating' => 3, 'review' => 'Layar 220 nits redup di ruangan terang. Tapi di dalam ruangan cukup.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'BatteryLife', 'rating' => 4, 'review' => 'Baterai tahan 7 jam untuk Excel & browsing. Cukup untuk workation.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'UpgradeMaster', 'rating' => 4, 'review' => 'Bisa tambah RAM sampai 32GB & SSD 1TB. Fleksibel untuk upgrade.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'DesignLover', 'rating' => 4, 'review' => 'Desain profesional dengan logo HP elegan. Cocok buat eksekutif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker kurang bass, meeting online harus pakai headset.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'PriceDebate', 'rating' => 4, 'review' => '11.5 juta agak mahal, tapi garansi 3 tahun + durability worth it.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'OfficePro', 'rating' => 4, 'review' => 'Bodi aluminium kokoh & keyboard nyaman. Cocok buat kerja 8 jam sehari.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'MultitaskHater', 'rating' => 3, 'review' => 'RAM 8GB kurang buka 15 tab Chrome. Upgrade ke 16GB wajib!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'SecurityMind', 'rating' => 5, 'review' => 'HP Sure Start + fingerprint sensor. Aman buat data perusahaan!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Port lengkap: USB-C, HDMI, LAN. Tidak perlu repot pakai dongle!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'ScreenHater', 'rating' => 3, 'review' => 'Layar 220 nits redup di ruangan terang. Tapi di dalam cukup.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'BatteryLife', 'rating' => 4, 'review' => 'Baterai tahan 7 jam buat Excel & browsing. Charger 65W cepat!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'UpgradeMaster', 'rating' => 4, 'review' => 'Bisa tambah RAM sampai 32GB & SSD 1TB. Fleksibel untuk kantor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'DesignAdmirer', 'rating' => 5, 'review' => 'Desain profesional dengan logo HP elegan. Cocok buat meeting klien.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'AudioDisappointed', 'rating' => 2, 'review' => 'Speaker suara pecah. Meeting online harus pakai headset.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 16, 'responder_name' => 'PriceDebate', 'rating' => 4, 'review' => '11.5 juta agak mahal, tapi garansi 3 tahun & durability worth it.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 17
            ['laptop_id' => 17, 'responder_name' => 'ProGamer', 'rating' => 5, 'review' => 'RTX 3080 + i9-11900H monster! Main Cyberpunk 2077 di 4K ultra 60fps. Layar 240Hz bikin gameplay mulus!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'HeatWarner', 'rating' => 4, 'review' => 'Suhu CPU tembus 90°C saat gaming berat. Wajib pakai cooling pad ekstra.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'PortableGamer', 'rating' => 5, 'review' => 'Bobot 2.1kg untuk laptop sekuat ini? Portabilitas level S+!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'BatteryHater', 'rating' => 2, 'review' => 'Baterai cuma 1.5 jam buat gaming. Tapi ya wajar untuk spek ini.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'RGBLover', 'rating' => 5, 'review' => 'Keyboard per-key RGB + logo MSI yang glow in the dark. Keren abis!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'NoiseComplaint', 'rating' => 3, 'review' => 'Kipas berisik seperti jet engine di mode Extreme Performance.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'UpgradeGeek', 'rating' => 5, 'review' => 'RAM 32GB + 2TB SSD bisa di-upgrade. Future-proof untuk 5 tahun!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'LinuxUser', 'rating' => 2, 'review' => 'Driver NVIDIA di Linux sering crash. Gaming paksa pakai Windows.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'PriceDebate', 'rating' => 4, 'review' => '35 juta mahal, tapi performa setara desktop high-end. Worth it!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'DesignHater', 'rating' => 4, 'review' => 'Desain terlalu "stealth", kurang warna. Tapi elegan sih.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'ProGamer', 'rating' => 5, 'review' => 'RTX 3080 + i9-11900H monster! Main Cyberpunk 2077 di 4K ultra 60fps. Layar 240Hz smooth banget!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'HeatWarner', 'rating' => 4, 'review' => 'Suhu CPU tembus 92°C saat gaming berat. Wajib pakai cooling pad ekstra.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'PortableGamer', 'rating' => 5, 'review' => 'Bobot 2.1kg untuk spek ini? Portabilitas level S+! Layar anti-silau oke di outdoor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'BatteryHater', 'rating' => 2, 'review' => 'Baterai cuma 1.5 jam buat gaming. Tapi ya emang laptop gaming sih...', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'RGBLover', 'rating' => 5, 'review' => 'Keyboard per-key RGB + logo MSI glow-in-the-dark. Keren abis!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'NoiseComplaint', 'rating' => 3, 'review' => 'Kipas berisik seperti jet engine di mode Extreme Performance.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'UpgradeGeek', 'rating' => 5, 'review' => 'RAM 32GB & SSD 2TB bisa di-upgrade. Future-proof untuk 5 tahun!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'LinuxGamer', 'rating' => 2, 'review' => 'Driver NVIDIA di Arch Linux bermasalah. Paksa dual-boot Windows.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'PriceDebate', 'rating' => 4, 'review' => '35 juta mahal, tapi performa setara desktop high-end. Worth it!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 17, 'responder_name' => 'DesignHater', 'rating' => 4, 'review' => 'Desain terlalu "stealth", kurang warna. Tapi elegan sih.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 18
            ['laptop_id' => 18, 'responder_name' => 'VideoEditorPro', 'rating' => 5, 'review' => 'RTX 3070 + i7-11800H ngerender 8K di Premiere Pro cuma 15 menit! Layar 4K 100% DCI-P3 akurat!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'WeightHater', 'rating' => 3, 'review' => 'Bobot 2.3kg kurang ideal buat mobile. Tapi performa editing luar biasa.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'ColorMaster', 'rating' => 5, 'review' => 'Delta-E <1! Cocok buat color grading film dokumenter.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'PriceShocker', 'rating' => 2, 'review' => '28 juta? Tapi ya targetnya profesional yang butuh presisi warna.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'SilentWorker', 'rating' => 5, 'review' => 'Kipas nggak berisik saat rendering! Thermal design MSI emang juara.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'StorageKing', 'rating' => 5, 'review' => '2TB SSD + slot NVMe kedua. Simpan 500+ project tanpa khawatir!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'BatteryLife', 'rating' => 4, 'review' => 'Baterai tahan 6 jam buat Photoshop. Cukup untuk kerja mobile.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Thunderbolt 4 + HDMI 2.1. Konek 4 monitor sekaligus!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker datar, harus pakai headphone untuk editing audio.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'LinuxPro', 'rating' => 5, 'review' => 'Driver NVIDIA Studio + Ubuntu kompatibel. Bisa CUDA + OpenCL!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => '3DArtistPro', 'rating' => 5, 'review' => 'RTX 3070 + i7-11800H ngerender Blender 2x lebih cepat! Layar 4K 100% DCI-P3 akurat!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'WeightHater', 'rating' => 3, 'review' => 'Bobot 2.3kg kurang ideal buat mobile. Tapi performa editing luar biasa.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'ColorMaster', 'rating' => 5, 'review' => 'Delta-E <1! Cocok buat color grading film dokumenter & foto profesional.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'PriceShocker', 'rating' => 2, 'review' => '28 juta? Tapi ya targetnya profesional yang butuh presisi warna.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'SilentWorker', 'rating' => 5, 'review' => 'Kipas nggak berisik saat rendering foto. Thermal design MSI juara!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'StorageKing', 'rating' => 5, 'review' => '2TB SSD bikin lega! Bisa simpan 500+ project tanpa khawatir.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'BatteryLife', 'rating' => 4, 'review' => 'Baterai tahan 6 jam buat Photoshop. Cukup untuk kerja mobile.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'Thunderbolt 4 & HDMI 2.1 lengkap! Konek 4 monitor sekaligus.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'AudioHater', 'rating' => 3, 'review' => 'Speaker datar, harus pakai headphone studio untuk mixing audio.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 18, 'responder_name' => 'LinuxPro', 'rating' => 5, 'review' => 'Driver NVIDIA Studio di Ubuntu stabil. Bisa CUDA acceleration!', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 19
            ['laptop_id' => 19, 'responder_name' => 'StudentLife', 'rating' => 4, 'review' => 'Ringan 1.3kg & baterai 10 jam! Cocok buat kuliah online.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'CasualGamer', 'rating' => 2, 'review' => 'Intel Iris Xe cuma kuat main Stardew Valley. Jangan harap game AAA!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'OfficeUser', 'rating' => 5, 'review' => 'SSD 512GB bikin startup cepat. Windows 11 lancar buat tugas kantor.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'BuildHater', 'rating' => 3, 'review' => 'Bodi plastik mudah baret. Tapi harga 12.5 juta masih oke.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'TravelStudent', 'rating' => 5, 'review' => 'Portabel banget! Charger kecil & USB-C mendukung power delivery.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'UpgradeFail', 'rating' => 2, 'review' => 'RAM soldered & storage fixed. Tidak bisa di-upgrade!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'WebcamUser', 'rating' => 4, 'review' => 'Webcam 720p cukup buat Zoom, tapi noise reduction kurang baik.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'BatteryFan', 'rating' => 5, 'review' => 'Baterai tahan seharian kuliah! Nggak perlu bawa charger.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'AudioLover', 'rating' => 3, 'review' => 'Speaker kurang bass, tapi suara jernih buat podcast.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'LinuxStarter', 'rating' => 5, 'review' => 'Driver Intel + Linux Mint stabil. Cocok buat programming!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'StudentLife', 'rating' => 4, 'review' => 'Ringan 1.3kg & baterai 10 jam! Cocok buat kuliah online.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'GamerDisappointed', 'rating' => 2, 'review' => 'Intel Iris Xe cuma kuat main Stardew Valley. Jangan harap game AAA!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'OfficeUser', 'rating' => 5, 'review' => 'SSD 512GB bikin Windows 11 cepat. Cocok buat tugas & Zoom meeting.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'BuildHater', 'rating' => 3, 'review' => 'Bodi plastik mudah baret. Tapi harga 12.5 juta masih oke.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'TravelStudent', 'rating' => 5, 'review' => 'Portabel banget! Charger kecil & USB-C support power delivery.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'UpgradeFail', 'rating' => 2, 'review' => 'RAM soldered & storage fixed. Tidak bisa di-upgrade!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'WebcamUser', 'rating' => 4, 'review' => 'Webcam 720p cukup buat Zoom, tapi noise reduction kurang baik.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'LinuxStarter', 'rating' => 5, 'review' => 'Driver Intel kompatibel dengan Linux Mint. No issue!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'AudioLover', 'rating' => 3, 'review' => 'Speaker kurang bass, tapi suara jernih buat podcast.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 19, 'responder_name' => 'DesignFan', 'rating' => 4, 'review' => 'Desain minimalis dengan bezel tipis. Layar 14" nyaman buat nugas.', 'created_at' => now(), 'updated_at' => now()],
            //Laptop ID 20
            ['laptop_id' => 20, 'responder_name' => 'OfficePro', 'rating' => 4, 'review' => 'Desain elegan & bobot 1.4kg. Baterai tahan 9 jam untuk kerja mobile.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'PerformanceHater', 'rating' => 3, 'review' => 'i7-1195G7 kurang buat render video 4K. Tapi SSD 1TB membantu.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'USB-C Thunderbolt 4 + microSD reader. Lengkap buat presentasi!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'ScreenHater', 'rating' => 4, 'review' => 'Layar 300 nits cukup terang, tapi warna agak over-saturated.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'SecurityMind', 'rating' => 5, 'review' => 'Fingerprint sensor + webcam shutter. Aman untuk data sensitif!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'UpgradeMaster', 'rating' => 2, 'review' => 'RAM soldered & storage fixed. Tidak bisa di-upgrade sama sekali!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'DesignAdmirer', 'rating' => 5, 'review' => 'Bodi aluminium rose gold mewah! Cocok buat eksekutif.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'AudioDisappointed', 'rating' => 3, 'review' => 'Speaker kecil, bass kurang. Meeting online harus pakai headset.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'PriceDebate', 'rating' => 4, 'review' => '19.5 juta agak mahal, tapi desain premium & portabilitas worth it.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'LinuxUser', 'rating' => 5, 'review' => 'Kompatibel sempurna dengan Ubuntu. Driver Intel nggak bermasalah!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'OfficePro', 'rating' => 4, 'review' => 'Desain elegan rose gold & berat 1.4kg. Baterai tahan 9 jam!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'PerformanceHater', 'rating' => 3, 'review' => 'i7-1195G7 kurang buat render video 4K. Tapi SSD 1TB membantu.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'PortLover', 'rating' => 5, 'review' => 'USB-C Thunderbolt 4 + microSD reader. Lengkap buat presentasi!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'SecurityMind', 'rating' => 5, 'review' => 'Fingerprint sensor + webcam shutter. Aman untuk data sensitif!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'ScreenHater', 'rating' => 4, 'review' => 'Layar 300 nits cukup terang, tapi warna agak over-saturated.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'UpgradeMaster', 'rating' => 2, 'review' => 'RAM soldered & storage fixed. Tidak bisa di-upgrade sama sekali!', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'DesignAdmirer', 'rating' => 5, 'review' => 'Bodi aluminium premium! Cocok buat eksekutif yang suka gaya.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'AudioDisappointed', 'rating' => 3, 'review' => 'Speaker kecil, bass kurang. Meeting online harus pakai headset.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'PriceDebate', 'rating' => 4, 'review' => '19.5 juta agak mahal, tapi desain & portabilitas worth it.', 'created_at' => now(), 'updated_at' => now()],
            ['laptop_id' => 20, 'responder_name' => 'LinuxUser', 'rating' => 5, 'review' => 'Kompatibel sempurna dengan Ubuntu. Driver Intel stabil!', 'created_at' => now(), 'updated_at' => now()],
        ];

        Review::insert($reviews);
    }
}